NORTH = [0, -1]
SOUTH = [0, 1]
EAST = [1, 0]
WEST = [-1, 0]
DIRECTIONS = [NORTH, SOUTH, EAST, WEST]
DOMAIN_SETTING = "domain/example_domain"
REWARD_DELIVERY = 10
REWARD_ERROR = -5
REWARD_MOVE = -1
REWARD_TARGET = 10
REWARD_PASSENGER = 10
PASSENGER_COLOR = "R"
ITERATION_LEARNING = 1

