NORTH = [-1, 0]
SOUTH = [1, 0]
EAST = [0, 1]
WEST = [0, -1]
DIRECTIONS = [NORTH, SOUTH, EAST, WEST]
DOMAIN_SETTING = "domain/example_domain"
REWARD_DELIVERY = 10
REWARD_ERROR = -5
REWARD_MOVE = -1
REWARD_TERMINAL = 10
REWARD_TARGET = 10
REWARD_PASSENGER = 10
PASSENGER_COLOR = "R"
ITERATION_LEARNING = 500
FONTSIZE = 30

